version: 2

defaults: &defaults
  working_directory: ~/plek
  docker:
    - image: circleci/node:8

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/plek
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/plek
      - run:
          name: Run integration and unit tests
          command: npm run test:ci

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/plek
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
          working_directory: packages/cli

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/plek
      - run:
          name: Deploy documentation website
          command: |
            npm run build
            cd docs/.vuepress/dist
            ../../../../packages/cli/src/main.js now plek.now.sh --team devoorhoede --app 'plek-website'
          working_directory: website
      - run:
          name: Deploy server
          command: ../cli/src/main.js now plek-server.now.sh --team devoorhoede --app 'plek-server'
          working_directory: packages/server

workflows:
  version: 2
  setup-publish:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - setup
      - test:
          requires:
            - deploy
      - publish:
          requires:
            - setup
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
